# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-26 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='status_choices',
            new_name='status',
        ),
    ]
